import { StyleSheet } from "react-native";

export default StyleSheet.create({
  parentShadowBox: {
    padding: 15,
    borderTopWidth: 0.5,
    borderColor: "#f3f3f3",
    borderRadius: 10,
    shadowOpacity: 1,
    elevation: 5,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowColor: "rgba(0, 0, 0, 0.1)",
    borderStyle: "solid",
    backgroundColor: "#fff",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  frameBg: {
    backgroundColor: "#ff0000",
    overflow: "hidden",
  },
  parentSpaceBlock1: {
    marginTop: 15,
    alignSelf: "stretch",
  },
  searchTypo: {
    color: "#afafaf",
    fontSize: 13,
    fontWeight: "400",
    textAlign: "left",
  },
  parentSpaceBlock: {
    paddingHorizontal: 5,
    flexDirection: "row",
  },
  switchTypo: {
    color: "#000",
    fontSize: 14,
    textAlign: "left",
  },
  headerChild: {
    overflow: "hidden",
    color: "#fff",
    height: 18,
    width: 18,
  },
  buttonContainer: {
    width: 25,
  },
  displayControl: {
    fontSize: 19,
    fontWeight: "600",
    color: "#fff",
    textAlign: "left",
  },
  header: {
    height: 72,
    paddingHorizontal: 17,
    paddingTop: 20,
    paddingBottom: 20,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "stretch",
  },
  frameChild: {
    height: 24,
    width: 24,
    backgroundColor: "#ff0000",
  },
  selectZoneParent: {
    alignSelf: "stretch",
    borderTopWidth: 0.5,
    borderColor: "#f3f3f3",
    borderRadius: 10,
    shadowOpacity: 1,
    elevation: 5,
    shadowRadius: 5,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowColor: "rgba(0, 0, 0, 0.1)",
  },
  frameItem: {
    width: 16,
    height: 16,
  },
  search: {
    marginLeft: 15,
  },
  frameGroup: {
    alignItems: "center",
    flexDirection: "row",
  },
  frameParent: {
    padding: 15,
    borderTopWidth: 0.5,
    borderColor: "#f3f3f3",
    borderRadius: 10,
    shadowOpacity: 9,
    elevation: 5,
    shadowRadius: 15,
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowColor: "#101010",
    borderStyle: "solid",
    backgroundColor: "#fff",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  frameParentdd: {
    padding: 15,
    paddingVertical: 18,
    borderTopWidth: 0.5,
    borderColor: "#f3f3f3",
    borderRadius: 10,
    shadowOpacity: 9,
    elevation: 5,
    shadowRadius: 15,
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowColor: "#101010",
    borderStyle: "solid",
    backgroundColor: "#fff",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  showingAllArticle: {
    fontWeight: "500",
    fontSize: 14,
  },
  switch: {
  },
  vectorIcon: {
    width: 20,
    height: 14,
    marginLeft: 10,
  },
  switchParent: {
    paddingVertical: 0,
    alignItems: "center",
  },
  showingAllArticleParent: {
    paddingTop: 15,
    marginTop: 15,
    alignSelf: "stretch",
    justifyContent: "space-between",
    paddingHorizontal: 5,
  },
  contentBoardChild: {
    height: 294,
  },
  contentBoard: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: "#f5f5f5",
    borderColor: "#e2e2e2",
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingBottom: 10,
    marginTop: -1,
    borderStyle: "solid",
    paddingTop: 20,
    alignSelf: "stretch",
    flex: 1,
  },
  mainPagefinal: {
    backgroundColor: "#000",
    width: "100%",
    height: 750,
    minWidth: 360,
    minHeight: 750,
    flex: 1,
  },
});
