import { StyleSheet } from "react-native";

export default StyleSheet.create({
  headerFlexBox: {
    alignItems: "center",
    alignSelf: "stretch",
  },
  checklistTypo: {
    fontWeight: "600",
    textAlign: "left",
  },
  contentShadowBox: {
    paddingVertical: 17,
    paddingHorizontal: 20,
    overflow: "hidden",
    backgroundColor: "#fff",
    borderRadius: 18,
    shadowRadius: 5,
    shadowColor: '#111111',
    elevation: 10,
    shadowOpacity: 9,
    shadowOffset: {
      width: 0,
      height: 20,
    },
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "stretch",
    justifyContent: "space-between",
  },
  backButtonIcon: {
    width: 24,
    height: 22,
  },
  checklist: {
    fontSize: 19,
    color: "#fff",
    textAlign: "left",
  },
  topCtaGrouping: {
    width: 25,
    height: 24,
    minWidth: 25,
  },
  header: {
    height: 72,
    justifyContent: "center",
    paddingHorizontal: 17,
    paddingTop: 20,
    paddingBottom: 20,
    zIndex: 0,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
  },
  ramChecklist: {
    fontSize: 17,
    color: "#000",
    textAlign: "left",
  },
  informationsChild: {
    backgroundColor: "#9d9d9d",
    width: 35,
    height: 1,
    marginTop: 9,
  },
  checklistForRam: {
    fontSize: 12,
    color: "#9a9a9a",
    marginTop: 9,
    textAlign: "left",
  },
  informations: {
    width: 170,
  },
  contentBoxChild: {
    color: 'black',
    width: 51,
    height: 51,
    marginLeft: 65,
  },
  contentBox1: {
    marginTop: 18,
  },
  contentBoard: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: "#f5f5f5",
    padding: 20,
    zIndex: 1,
    marginTop: -1,
    alignItems: "center",
    alignSelf: "stretch",
    flex: 1,
  },
  addButton: {
    position: "absolute",
    top: 678,
    left: 290,
    shadowColor: "rgba(0, 0, 0, 0.25)",
    shadowRadius: 4,
    elevation: 4,
    width: 50,
    height: 50,
    display: "none",
    zIndex: 2,
    shadowOpacity: 1,
    shadowOffset: {
      width: 0,
      height: 3,
    },
  },
  landingPage: {
    backgroundColor: "#000",
    width: "100%",
    height: 750,
    minWidth: 360,
    minHeight: 750,
    flex: 1,
  },
});
